### ISSUE TITLE
Using ~/.lispkitrc doesn't seem to bind keys?

### ISSUE THREAD

**Issue by ahungry** [AeroNotix/lispkit#72]
Just looking at the project and I find the default key binds not very great coming from vimprobable2/firefox+pentadactyl.

I attempted to add the following into my ~/.lispkitrc but it runs into undefineds and halts the REPL before loading the browser:

```lisp
(define-key *top-map* "o" "browse-url")
```

What type of settings are expected to go in this file?

**Comment by jorams** [comment]
@ahungry The problem is probably that your `~/.lispkitrc` doesn't have `(in-package :lispkit)` at the top.

**Comment by Ralt** [comment]
> What type of settings are expected to go in this file?

These are not settings, it's literally a lisp file which code is executed. (much more powerful :-))

See @jorams's suggestion for a common error.

**Comment by ahungry** [comment]
Yup, that was it, thanks guys.
