### ISSUE TITLE
This SBCL does not support core compression

### ISSUE THREAD

**Issue by jemc** [AeroNotix/lispkit#84]
On Fedora 20, with sbcl installed via the package manager (`yum`):
```bash
$ make
Fatal SIMPLE-ERROR:
  This SBCL does not support core compression
make: *** [/home/jemc/1/code/gitx/lispkit/lispkit] Error 1
```
```bash
SBCL 1.1.12-1.fc20
```

If I remove the `--compress-core` from the Makefile, it complies and compiles.

I'd hope there was a way to detect the lack of compression support and abort automatically without me having to edit the Makefile, but I know next-to-nothing about lisp systems.

**Comment by AeroNotix** [comment]
Hi,

I made some changes to detect whether SBCL supports compression, could you check this please?

**Comment by jemc** [comment]
It works, thanks.
