### ISSUE TITLE
Infinite windows

### ISSUE THREAD

**Issue by LaloHao** [AeroNotix/lispkit#88]
I loaded the asdf system from my quicklisp to avoid downloading duplicates packages with the `make` command, i got no errors at all, and i managed to run `(lispkit:main)` and `(lispkit:do-main)` with the same results: it starts opening infinite lispkit windows until i kill the process with "pkill -9 sbcl"

This also happens when i compile with help of the Makefile and run `./lispkit`.

This happens on both StumpWM and XFCE4

In the console, i get the following errors:
```sh
(lispkit:24082): Gtk-WARNING **: Overriding tab label for notebook

(lispkit:24082): Gtk-WARNING **: Overriding tab label for notebook

(lispkit:24082): Gtk-WARNING **: Attempting to add a widget with type GtkLabel to a container of type GtkBox, but the widget is already inside a container of type GtkBox, please remove the widget from its existing container first.

(process:24092): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'SoupCookieJar'

(process:24092): libsoup-CRITICAL **: soup_cookie_jar_get_cookies: assertion 'SOUP_IS_COOKIE_JAR (jar)' failed
```

**Comment by AeroNotix** [comment]
What version(s) of webkit are you using?

**Comment by LaloHao** [comment]
Latest commit: 86f464b596553cbee9639ba83722624607df61c3

**Comment by AeroNotix** [comment]
@LaloHao webkit, not lispkit. Which version of webkit are you using?

**Comment by LaloHao** [comment]
Sorry, that triggered my dyslexia.

I tried 3 webkit packages from the Arch Linux Repositories:
webkit2gtk-2.12.2-1
webkitgtk-2.4.11-1
webkitgtk2-2.4.11-1

They seem to deliver these libraries (respectively)
libwebkit2gtk-4.0.so
libwebkitgtk-3.0.so
libwebkitgtk-1.0.so

**Comment by AeroNotix** [comment]
And you have the issue on all versions of the library?

Did you build lispkit manually? `make` should give you everything you need.

Do you have any custom configuration?

**Comment by LaloHao** [comment]
The only one that compiles with `make` is **libwebkit2gtk-4.0.so** (_webkit2gtk-2.12.2-1_), the other two says `target 'deps' failed`.

I haven't modified any file, i literally cloned lispkit and executed `make`

**Comment by AeroNotix** [comment]
I'll check it out myself, thanks for the notification.

**Comment by AeroNotix** [comment]
@LaloHao I tried it myself and it compiled and I did not get infinite windows.

Can you clone clean and do `make deps` and put all the output in this ticket, please?

**Comment by LaloHao** [comment]
It's strange: `make` success but `make deps` fails

I think quicklisp is not downloading
This is the output
```shell
Unhandled SB-INT:SIMPLE-FILE-ERROR in thread #<SB-THREAD:THREAD
                                               "main thread" RUNNING
                                                {1002AACD43}>:
  Couldn't load
  #P"/home/hao/dev/lisp/lispkit/.quicklocal/quicklisp/setup.lisp": file does
  not exist.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1002AACD43}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {1002ACC8EB}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {1002ACC8BB}>)
3: (PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDERR* {100016B503}> :START 0 :FROM :INTERRUPTED-FRAME :COUNT NIL :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-INT:SIMPLE-FILE-ERROR "~@<Couldn't load ~S: file does not exist.~@:>" {1002AB4183}> #<unavailable argument>)
5: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-INT:SIMPLE-FILE-ERROR "~@<Couldn't load ~S: file does not exist.~@:>" {1002AB4183}>)
6: (INVOKE-DEBUGGER #<SB-INT:SIMPLE-FILE-ERROR "~@<Couldn't load ~S: file does not exist.~@:>" {1002AB4183}>)
7: (ERROR SB-INT:SIMPLE-FILE-ERROR :PATHNAME #P"/home/hao/dev/lisp/lispkit/.quicklocal/quicklisp/setup.lisp" :FORMAT-CONTROL "~@<Couldn't load ~S: file does not exist.~@:>" :FORMAT-ARGUMENTS (#P"/home/hao/dev/lisp/lispkit/.quicklocal/quicklisp/setup.lisp"))
8: (LOAD #P"/home/hao/dev/lisp/lispkit/.quicklocal/quicklisp/setup.lisp" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
9: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:LOAD . "/home/hao/dev/lisp/lispkit/.quicklocal/quicklisp/setup.lisp") (:EVAL . "(push \"/home/hao/dev/lisp/lispkit/\" asdf:*central-registry*)") (:EVAL . "(ql:quickload :lispkit)") (:EVAL . "(quit)")))
10: (SB-IMPL::TOPLEVEL-INIT)
11: ((FLET #:WITHOUT-INTERRUPTS-BODY-82 :IN SAVE-LISP-AND-DIE))
12: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
Makefile:80: fallo en las instrucciones para el objetivo 'deps'
make: *** [deps] Error 1
```

**Comment by AeroNotix** [comment]
How are you invoking the Makefile?

Try just using `make` alone.

**Comment by AeroNotix** [comment]
I just fixed the `make deps` target with 2482dbeabc79667407dabe7765dfbffc16584b08 to have the correct dependency targets to build Quicklisp beforehand.

**Comment by LaloHao** [comment]
Previous output is from `make deps`

If i do `make` alone i get a larger output (with no errors)
https://gist.github.com/LaloHao/247ea5b96ebb9c0b211ec8d29ec66a52

Here's `make deps` again with 2482dbeabc79667407dabe7765dfbffc16584b08
https://gist.github.com/LaloHao/6f5117e989a30911cc3468d755fbce8b

**Comment by AeroNotix** [comment]
That's the correct output. Everything looks like it's building fine.

Next step:

What are the keys you press to trigger the infinite loop?

**Comment by LaloHao** [comment]
I dont get the chance to do/press anything before the windows start poping up

I just run `./lispkit` and then it happens

**Comment by AeroNotix** [comment]
Any chance you could get me a short video of it happening?

**Comment by LaloHao** [comment]
https://youtu.be/u7qFUvUar4I

**Comment by LaloHao** [comment]
This was probably caused by some WM i had installed, i formatted my computer and the problem seems to be fixed

**Comment by AeroNotix** [comment]
Great! I had this in my todo list and occasionally tried to reproduce with no results. Glad it's fixed!

**Comment by LaloHao** [comment]
I had installed several WM (i3wm, stumpwm) and DE (xfce, kde, gnome, lxde) to test them, one of them or most likely the combination of them screwed it up
