### ISSUE TITLE
Building Problem

### ISSUE THREAD

**Issue by vtomole** [AeroNotix/lispkit#89]
Hey I'm having trouble build lisp kit, I'm getting:unhandled condition in --disable-debugger mode, quitting
;
; compilation unit aborted
; caught 2 fatal ERROR conditions
Makefile:80: recipe for target 'deps' failed
make: \* [deps] Error 1

**Comment by AeroNotix** [comment]
What OS? What CL? 

Does `make deps` work on its own?

**Comment by vtomole** [comment]
I have Ubuntu 16.04. I previously had Clisp , but then I sudo-apt removed it and sudo-apt installed SBCL. I got the same error with make separate.

**Comment by AeroNotix** [comment]
CLISP isn't supported at all. You should use JUST SBCL and make sure it is using SBCL.

Can you give me the full shell output of both `make` and `make deps`, please?

**Comment by vtomole** [comment]
This is what make deps got me:http://pastebin.com/7ztTaNnE

**Comment by AeroNotix** [comment]
@vtomole you need to install a package which provides `libwebkit2gtk`

**Comment by AeroNotix** [comment]
https://github.com/AeroNotix/lispkit#requirements ensure you meet all these requirements.

**Comment by vtomole** [comment]
This is what  running makes gets me:http://pastebin.com/797zTCWK.

I used sudo apt-get -y install libwebkitgtk-1.0-0 libwebkitgtk-3.0-0 and I'm still getting the same error.

**Comment by vtomole** [comment]
I also did:sudo apt-get install gtk2.0 and sudo apt-get install sqlite3 libsqlite3-dev.

**Comment by AeroNotix** [comment]
libwebkit**2**gtk

**Comment by vtomole** [comment]
I'm sorry I can't read :(. Haha it finally built!  Thank you!  You  mentioned that you don't plan on making this windows compatible. I was wondering , how hard it would be to make that happen? I could try to do it.

**Comment by AeroNotix** [comment]
@vtomole I honestly don't know what would need to be done entirely. However, it would need some way to make the cffi interfaces work and ensure that it's clear what packages need to get installed there to make it work. 

SBCL is on Windows, C is on Windows so I don't really know what else it needs to make it work. It's more a case of someone doing the work to get it there. You can try yourself, by all means! I'll merge anything that demonstrably works.

**Comment by vtomole** [comment]
Do you know about closure? https://github.com/dym/closure. If you do I'm wondering if it's rendering engine was written completely in Lisp. If so then,  that's awesome! It's a shame that it seems abandoned

**Comment by gabriel-laddel** [comment]
@vtomole I looked into closure not terribly long ago. All it needs is someone to hunt down the correct versions of the libraries it depends on (ie, sit around on a git GUI for a day, jumping around commits).

**Comment by vtomole** [comment]
I think it's amazing that the whole project is under 100,000 lines. I mean it must not be that complex considering that big engines like WebKit are millions of lines. I just checked servo(a new engine from Mozilla:https://github.com/servo/servo) and it seems to be just over 15,000 lines.( I know counting projects by lines doesn't do the projects justice, I'm just trying to get a general idea of how big they are)

**Comment by gabriel-laddel** [comment]
@vtomole It's in CL, running on the best graphics library known to man. Lotsa fun.

**Comment by AeroNotix** [comment]
@vtomole the original issue is fixed, right? If you want to pursue alternate things such as building on Windows then feel free to open another ticket to track that. :+1:

**Comment by vtomole** [comment]
Yup :D

**Comment by gabriel-laddel** [comment]
@vtomole yo, come hang out in #clim on freenode. Logs link: http://irclog.tymoon.eu/freenode/%23clim
