### ISSUE TITLE
Try to make lispkit work on windows

### ISSUE THREAD

**Issue by vtomole** [AeroNotix/lispkit#90]
All discussions about how to make lispkit work on windows will be here. This might be very difficult, but it's worth trying!

**Comment by AeroNotix** [comment]
First step is just trying to run `make` on a Windows box.

**Comment by vtomole** [comment]
Install MSY2 https://msys2.github.io/

**Comment by vtomole** [comment]
Install SBCL: https://github.com/akovalenko/sbcl-win32-threads/wiki, I used that one, but the normal website is also valid http://www.sbcl.org/platform-table.html

**Comment by vtomole** [comment]
Problem to solve: When you try make for lispkit in MSY2, it doesn't detect the SBCL installation. Something about setting PATH variables could solve it?

**Comment by vtomole** [comment]
In fact, how about trying "export PATH"command in MSY2 to point to the sbcl.exe, I'm not experienced in doing this, can you try it?

**Comment by AeroNotix** [comment]
You would just need to do:

`export PATH=$PATH:/path/to/sbcl/directory/`

**Comment by vtomole** [comment]
What I got when I ran make on Cygwin:http://pastebin.com/PecYLcLx

**Comment by PuercoPop** [comment]
@vtomole For SBCL try using [Mingw](http://www.mingw.org/) instead

**Comment by vtomole** [comment]
@PuercoPop  Cygwin seems to be working fine for SBCL and Make, I'm just having build errors now.

**Comment by vtomole** [comment]
@AeroNotix I've tried it on a different machine and I'm still getting the same error.

**Comment by AeroNotix** [comment]
Can you list exactly what packages you've installed on windows to get to the point where you are now?

**Comment by vtomole** [comment]
@AeroNotix  
I've installed cygwin:https://www.cygwin.com/, cygwin lets you run make in windows
I've also installed sbcl for windows:http://www.sbcl.org/platform-table.html
when i run make the first time it fails and when i run it a second time it gives the error that i posted in paste bin above.

**Comment by vtomole** [comment]
@AeroNotix I was in an IRC chat and someone said that installing clim on windows is tricky and could be impossible, so this could be what's happening right now.
